spring.application.name=logging_middleware
server.port=8080
app.email=${APP_EMAIL}
app.name=${APP_NAME}
app.rollNo=${ROLL_NO}
app.accessCode=${ACCESS_CODE}
app.clientId=${CLIENT_ID}
app.clientSecret=${CLIENT_SECRET}
app.registerUrl=${REGISTER_URL}
app.authUrl=${AUTH_URL}
app.logUrl=${LOG_URL}